services:
  apache:
    build: ./
    labels:
      - "traefik.backend=alpine"
      - "traefik.frontend.rule=Host:alpine.docker.localhost"
    environment:
      - MYSQL_HOST=mysql
      - APACHE_SERVER_NAME=alpine.docker.localhost
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_HTML_ERRORS=On
      - PHP_XDEBUG_ENABLED=true
    networks:
      - default
    ports:
      - "${PORT_NUMBER:-8989}:80"
    volumes:
      - ./public:/app/public
    cap_add:
      - SYS_TIME
      - SYS_NICE

networks:
  default:
    driver: bridge
